name: branch bottest

on:
  push:
    branches:
      - '*'
      - '!master'
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'env.sh'

jobs:
  bottest:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      -
        name: Docker build cuberite
        run:  docker build --tag cuberite .
      -
        name: Docker build testbot
        run: docker build --tag testbot testbot
      -
        name: Create docker network
        run: docker network create mine
      -
        name: Run cuberite
        run:  docker run --name cuberite --network mine --publish 25565:25565 --detach --tty cuberite
      -
        name: Run testbot
        run:  docker run --network mine testbot localhost
      -
        name: Validate server logs
        run: |
          docker logs cuberite | grep --fixed-strings 'testbot has joined'
          docker logs cuberite | grep --fixed-strings 'Servus!'
          docker logs cuberite | grep --fixed-strings 'testbot has left'
          
          
