name: branch bottest

on:
  push:
    branches:
      - '*'
      - '!master'
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'env.sh'

jobs:
  cuberite-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref:  ${{ github.ref }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/mehmetahsen/cuberite:${{ github.sha }}
  bottest:
    name:     Check if a bot can join the game and say hi
    runs-on:  ubuntu-latest
    needs:    cuberite-build
    services:
      cuberite:
        image:  ghcr.io/mehmetahsen/cuberite:${{ github.sha }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref:  ${{ github.ref }}
      -
        name: Docker build testbot
        run:  docker build --tag testbot testbot
      -
        name: Run testbot
        run:  docker run testbot localhost
      -
        name: Validate server logs
        run: |
          docker logs cuberite | grep --fixed-strings 'testbot has joined'
          docker logs cuberite | grep --fixed-strings 'Servus!'
          docker logs cuberite | grep --fixed-strings 'testbot has left'
