name: branch bottest

on:
  push:
    branches:
      - '*'
      - '!master'
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'env.sh'

jobs:
  cuberite-build:
    name:     Build & Push Cuberite 
    runs-on:  ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref:  ${{ github.ref }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GP_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/mehmetahsen/cuberite-docker:${{ github.sha }}
  bottest:
    name:     Test with a bot
    runs-on:  ubuntu-latest
    needs:    cuberite-build
    services:
      cuberite:
        image:  ghcr.io/mehmetahsen/cuberite-docker:${{ github.sha }}
        ports:
          - 25565:25565
        options: '--tty'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref:  ${{ github.ref }}
      -
        name: Docker build testbot
        run:  docker build --tag testbot testbot
      -
        name: Run testbot
        run:  docker run --network host testbot
      -
        name: Validate server logs
        run: |
          echo "::debug:: `docker logs ${{ job.services.cuberite.id }}`"
          docker logs ${{ job.services.cuberite.id }} | grep --fixed-strings 'testbot has joined'
          docker logs ${{ job.services.cuberite.id }} | grep --fixed-strings 'Servus!'
          docker logs ${{ job.services.cuberite.id }} | grep --fixed-strings 'testbot has left'
