name: branch bottest

on:
  push:
    branches:
      - '*'
      - '!master'
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'env.sh'

jobs:
  bottest:
    name:     Test with a bot
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref:  ${{ github.ref }}
      - name: Docker build cuberite
        run: docker build --tag cuberite .
      - name: Docker build testbot
        run:  docker build --tag testbot testbot
      - name: Docker network create mine
        run: docker network create mine
      - name: Run cuberite
        run: |
          docker run --name cuberite --network mine \
            -e CREATE_SETTINGS_INI=1
            -e AUTHENTICATION_AUTHENTICATE=0
            --tty --detach
      - name: Run testbot
        run:  docker run --network mine testbot cuberite
      - name: Validate server logs
        run: |
          echo "::debug:: `docker logs cuberite"
          docker logs cuberite | grep --fixed-strings 'testbot has joined'
          docker logs cuberite | grep --fixed-strings 'Servus!'
          docker logs cuberite | grep --fixed-strings 'testbot has left'
